### ISSUE TITLE
Auto-deploy to pip

### ISSUE THREAD

**Issue by harterrt** [mozilla/docere#14]
Docere should be deployed to pypi whenever we release a tagged version. Travis-ci does this natively.

We should also include a cheat sheet of when and how to do the tagged release.

**Comment by shell1** [comment]
moz reports will automatically use the newest version if new content or rebuild manually

**Comment by tdsmith** [comment]
I think I'll declare this moot; we currently don't anticipate needing to actually execute docere anywhere except a development context or the mozilla-private-reports CI, so we can switch to always installing from the Github default branch instead of installing from pypi.
