### ISSUE TITLE
Use Semantic UI for styling?

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/docere#32]
At present, docere uses skeleton as barebone UI to power mpr and mr. to modernize for the knowledge repo work, I propose we use Semantic UI for styling. This will depart from the current implementation but the same underlying goal: provide a simple static site generator for reports and assets.

**Comment by tdsmith** [comment]
Do you have opinions about / why do you prefer Semantic vs Skeleton, Bootstrap, or something else?

**Comment by teonbrooks** [comment]
closing as Skeleton is good enough for now
