### ISSUE TITLE
Fix Docere core deployment CI

### ISSUE THREAD

**Issue by tdsmith** [mozilla/docere#33]
Deploying the test repository, which happens on commits to the master branch, fails with "Invalid S3 Access Key Id" from e.g. https://travis-ci.org/github/mozilla/docere/jobs/717048711#L317.

I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1662926 but it looks stuck.

**Comment by shell1** [comment]
Waiting for Jason.  CI pushed on merge to master failed because s3 key stored in travis broken.  need new key.

**Comment by tdsmith** [comment]
Done!
