### ISSUE TITLE
Document tag keys

### ISSUE THREAD

**Issue by tdsmith** [mozilla/docere#36]

**Comment by shell1** [comment]
DS have documentation on how to apply attributes to their reports

**Comment by tdsmith** [comment]
https://docs.google.com/document/d/118-wzA52UAFNa_2Nt9Kisst0_zREILZVin17vixfVTk/edit#heading=h.pmrew2j7u444 outlines some of the things we've provisionally decided about tags that we can translate into user-facing documentation.

**Comment by ksiegler1** [comment]
Updated the README file on Docere to reflect some tag attribute documentation. In our meeting this week I would like to discuss 1. the abbreviated tags and 2. the documentation itself. There's no PR to link to, hope that's okay?

**Comment by tdsmith** [comment]
> There's no PR to link to, hope that's okay?

It's fine for docs, though a couple of comments:
- I noticed you included some rendered HTML; it's sort of hard to view that directly and it's something that we'd have to keep updated separately from the Markdown source, so it's probably better to omit it
- There's a syntax error in your JSON example :) -- you're missing a comma after the end of the abstract.

The pull request workflow works well and I prefer to use it for all changes; we can optionally disable committing to the default branch except through pull requests.

**Comment by ksiegler1** [comment]
> I noticed you included some rendered HTML; it's sort of hard to view that directly and it's something that we'd have to keep updated separately from the Markdown source, so it's probably better to omit it

You're referencing the README.html file, correct? If so, I'll go ahead and delete that.

**Comment by ksiegler1** [comment]
Deleted extra file and added comma. Closing this issue.
