### ISSUE TITLE
Intermediate entry step - web form that looks like current deliverables.wiki

### ISSUE THREAD

**Issue by shell1** [mozilla/docere#61]
This is so users don't have to work out formating TOML by hand.  the form will spits out TOML formed for an entry - that gets pasted into github.

Need accompanying docs of what to do with TOML.

**Comment by tdsmith** [comment]
Closed by https://github.com/MozillaDataScience/jira-helper/commit/11614bc3cffae70007249f554c0fd999c63d6483 which lives at https://mozilladatascience.github.io/jira-helper/. It's just static HTML with a little Javascript so we can host this anywhere.
